name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "This is your first isssue. All issues are veiwed as soon as possible by @nikoniko78."
        pr-message: "This is your first pull request on scripts-java-physion! Thank you for the commitment!"
