name: Notify Discussions
on:
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  send-notification:
    runs-on: ubuntu-24.04  # Use the latest Ubuntu version to avoid warnings
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install jq
        run: sudo apt-get install -y jq  # Ensure jq is installed

      - name: Send notification to discussions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.commenter }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/${{ github.repository }}/discussions)
          if echo "$RESPONSE" | jq empty > /dev/null 2>&1; then
            echo "$RESPONSE" | jq -r '.[] | select(.state == "open") | .url' | while read -r url; do
              curl -s -H "Authorization: token ${{ secrets.commenter }}" \
                   -H "Accept: application/vnd.github.v3+json" \
                   -X POST \
                   -d '{"body":"The discussions tab is currently unresponsive."}' \
                   "${url}/comments";
            done
          else
            echo "Failed to parse JSON response from GitHub API. Exiting with error."
            exit 1
          fi
