name: Notify Discussions

on: workflow_dispatch

jobs:
  notify:
    runs-on: ubuntu-latest
    permissions:
      discussions: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Notify Discussions
        env:
          GITHUB_TOKEN: ${{ secrets.commenter }}
        run: |
          RESPONSE=$(curl -s -H "Authorization: token ${{ secrets.commenter }}" \
                            -H "Accept: application/vnd.github.v3+json" \
                            https://api.github.com/repos/${{ github.repository }}/discussions)
          echo "API response: $RESPONSE"
          echo "$RESPONSE" | grep -o '"url": "[^"]*' | grep -o '[^"]*$' | while read -r url; do
            curl -s -H "Authorization: token ${{ secrets.commenter }}" \
                 -H "Accept: application/vnd.github.v3+json" \
                 -X POST \
                 -d '{"body":"The discussions tab is currently unresponsive."}' \
                 "${url}/comments"
          done

            exit 1

          fi
